package com.cs319.backend.enums;

public enum NotificationType {
    PENDING_APPLICATION_FORM,
    UPCOMING_NOT_ASSIGNED_EVENT,
    WAITING_TRAINEE_PROMOTION,
    CONFIRMED_TOUR,
    CANCELLED_EVENT,
    OUTDATED_INFO
}
