package com.cs319.backend.enums;

public enum EmailType {
    GROUP_TOUR_CONFIRMATION,
    INDIVIDUAL_TOUR_CONFIRMATION,
    GUIDE_INFORMATION,
    TRAINEE_INFORMATION,
    ADVISOR_INFORMATION,
    COORDINATOR_INFORMATION,
    CANCELLED_EVENT,
    OUTDATED_INFO,
    MISSING_GUIDE,
    FAIR_ACCEPTANCE
}
