package com.example.demo.enums;

public enum Department {
    COMPUTER_ENGINEERING,
    ELECTRICAL_ENGINEERING,
    MECHANICAL_ENGINEERING,
    INDUSTRIAL_ENGINEERING,
    ARCHITECTURE,
    BUSINESS_ADMINISTRATION,
    ECONOMICS,
    MANAGEMENT_INFORMATION_SYSTEMS,
    MATHEMATICS,
    PHYSICS,
    CHEMISTRY,
    MOLECULAR_BIOLOGY,
    PSYCHOLOGY,
    LAW,
    INTERNATIONAL_RELATIONS,
    POLITICAL_SCIENCE_AND_PUBLIC_ADMINISTRATION,
    PHILOSOPHY,
    ENGLISH_LANGUAGE_AND_LITERATURE,
    ELECTRICAL_AND_ELECTRONICS_ENGINEERING,
    COMMUNICATION_DESIGN;
}
