package com.example.demo.enums;

public enum NotificationType {
    PENDING_APPLICATION_FORM,
    UPCOMING_NOT_ASSIGNED_EVENT,
    TRAINEE_COMPLETION_REACHED,
    GUIDE_ASSIGNED_TOUR,
    CANCELLED_EVENT,
    NEW_TOUR_CREATED,
    NEW_FAIR_CREATED,
    TRAINEE_PROMOTED,
    PASSWORD_RESET
}
