package com.example.demo.enums;

public enum NotificationType {
    PENDING_APPLICATION_FORM,
    UPCOMING_NOT_ASSIGNED_EVENT,
    TRAINEE_COMPLETION_REACHED,
    CONFIRMED_TOUR,
    CANCELLED_EVENT,
    NEW_TOUR_CREATED,
    NEW_FAIR_CREATED,
    GUIDE_FEEDBACK_RECEIVED,
    NEW_TRAINEE_ASSIGNED,
    EVENT_RESCHEDULED,
    REJECTED_FORM,
    ACCEPTED_FORM,
    TRAINEE_PROMOTED,
    PASSWORD_RESET
}
